import {Dimensions, Platform} from 'react-native';

let {height, width} = Dimensions.get('window');

export default {
  CONSTANTS: {
    HEIGHT: height,
    WIDTH: width,
    DEVICE: Platform.OS,
    SIZE_10: width * 0.029,
    SIZE_20: width * 0.049,
    SIZE_60: width * 0.145,
    SIZE_110: width * 0.266,
    SIZE_157: width * 0.38,
    SIZE_192: width * 0.464,
    SIZE_193: width * 0.62,
    SPACE_40: width * 0.097,
    SPACE_50: height * 0.01,
    SPACE_55: height * 0.062,
    SPACE_95: width * 0.23,
    SQUARE_50: width * 0.11,
    CIRCLE_36: width * 0.087,
    CIRCLE_37: width * 0.1,
    BOTTOM_TAB_84: width * 0.203,
    CARD_373: width * 0.903,
    CARD_460: width * 1.111,
    MODAL_316: width * 0.763,
    MODAL_157: width * 0.379,
    MODAL_194: width * 0.469,
    THUMB_381: width * 0.921,
    SIZE_426: height * 0.476,
    SIZE_538: height * 0.6,
    SIZE_801: height * 0.894,
    SIZE_854: height * 0.953,
    // SIZE_10: height * 0.11,
    WEIGHT_800: '800',
    WEIGHT_700: '700',
    WEIGHT_600: '600',
  },
  COLOR: {
    PRIMARY100: 'rgba(72, 74, 89, 1)',
    PRIMARY70: 'rgba(72, 74, 89, 0.7)',
    PRIMARY50: 'rgba(72, 74, 89, 0.5)',
    WARNING: 'rgba(249, 41, 40, 1)',
    WARNING_BORDER: 'rgba(251, 125, 123, 1)',
    SECONDARY: 'rgba(236, 178, 150, 1)',
    BLACK20: 'rgba(0, 0, 0, 0.2)',
    BLACK40: 'rgba(0, 0, 0, 0.4)',
    WHITE95: 'rgba(255, 255, 255, 0.95)',
    WHITE85: 'rgba(255, 255, 255, 0.85)',
    WHITE75: 'rgba(255, 255, 255, 0.75)',

    STATUS_INACTIVE: 'rgba(237, 238, 239, 1)',
    STATUS_ACTIVE: 'rgba(241, 194, 167, 1)',
    GOT: 'rgba(74, 144, 226, 1)',
    BACKGROUND: 'rgba(246, 246, 246, 6)',
    HEADER_BORDER: 'rgba(145, 202, 203, 1)',
    HEADER_TITLE: 'rgba(92, 95, 112, 1)',
    SETTING_ICON: 'rgba(82, 84, 100, 1)',
    CANCELRNUTEXT: '#4b4a5a',
    CANCELRUNEXIT: '#484a59',
    BLACK: '#000000',
  },
  //   IMAGE: {
  //     SPLASH: require('../assets/splash.png'),
  //     STOCK: {
  //       STOCK_1: require('../assets/Stock/group1.png'),
  //       STOCK_2: require('../assets/Stock/group2.png'),
  //       STOCK_3: require('../assets/Stock/man1.png'),
  //       STOCK_4: require('../assets/Stock/man2.png'),
  //       STOCK_5: require('../assets/Stock/man3.png'),
  //       STOCK_6: require('../assets/Stock/man4.png'),
  //       STOCK_7: require('../assets/Stock/man5.png'),
  //       STOCK_8: require('../assets/Stock/man6.png'),
  //       STOCK_9: require('../assets/Stock/man7.png'),
  //       STOCK_10: require('../assets/Stock/woman1.png'),
  //       STOCK_11: require('../assets/Stock/woman2.png'),
  //       STOCK_12: require('../assets/Stock/woman3.png'),
  //       STOCK_13: require('../assets/Stock/woman4.png'),
  //       STOCK_14: require('../assets/Stock/woman5.png'),
  //       STOCK_15: require('../assets/Stock/woman6.png'),
  //       STOCK_16: require('../assets/Stock/woman7.png'),
  //       STOCK_17: require('../assets/Stock/woman8.png'),
  //       STOCK_18: require('../assets/Stock/woman9.png'),
  //       STOCK_19: require('../assets/Stock/woman10.png'),
  //     },
  //     UNKNOWN: require('../assets/unknown.png'),
  //     LOADING: require('../assets/loading.gif'),
  //     TARGET: require('../assets/target.png'),
  //     LOCATION: require('../assets/location.png'),
  //     POSITION_BLACK: require('../assets/position-black.png'),
  //     POSITION_GRAY: require('../assets/position-gray.png'),
  //     RANK_BLACK: require('../assets/rank-black.png'),
  //     RANK_GRAY: require('../assets/rank-gray.png'),
  //     TRACE_BLACK: require('../assets/trace-black.png'),
  //     TRACE_GRAY: require('../assets/trace-gray.png'),
  //     CHART_BLACK: require('../assets/chart-black.png'),
  //     CHART_GRAY: require('../assets/chart-gray.png'),
  //     OPTION_SELECTED: require('../assets/option_selected.png'),
  //     OPTION_UNSELECTED: require('../assets/option_unselected.png'),
  //     // CHART_DISTANCE: require("../assets/Stock/chart_distance.png"),
  //     // CHART_AVERAGE: require("../assets/Stock/chart_average.png"),
  //   },
  /*FONT: {
    FUTURA: require('../App/assets/Fonts/Futura-Bold.otf'),
    SFProTextRegular: require('../App/assets/Fonts/SFProText-Regular.ttf'),
    SFProTextMedium: require('../App/assets/Fonts/SFProText-Medium.ttf'),
    SFProTextBold: require('../App/assets/Fonts/SFProText-Bold.ttf'),
  },*/
};
